spring.datasource.url=jdbc:postgresql://localhost:5432/SpaceXplore
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# spring.application.name=demo
# spring.jpa.hibernate.ddl-auto=update
# spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/spring?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
# # spring.datasource.username=${DB_USERNAME:dasuni}
# # spring.datasource.password=${DB_PASSWORD:DasuniPass123!}
# spring.datasource.username=${DB_USERNAME:root}
# spring.datasource.password=${DB_PASSWORD:SMWish}
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=8081

# CORS Configuration
app.cors.allowed-origins=http://localhost:3000,http://127.0.0.1:3000